spring.application.name=task
server.servlet.context-path=/api
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.config.import=optional:file:.env[.properties]

frontend.url=${FRONTEND_URL}
huggingface.access.token=${HF_ACCESS_TOKEN}
huggingface.text.api.url=${HF_TEXT_API_URL}
huggingface.model=${HF_MODEL}
